In [8]:
import pandas as pd

extinct_mammals_url = "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv"
exmam_df = pd.read_csv(extinct_mammals_url, index_col="Decade")
exmam_df

        Cumulative number of extinct mammal species
Decade
1790                                              0
1800                                              0
1810                                              0
1820                                              0
1830                                              0
1840                                              1
1850                                              3
1860                                              5
1870                                              7
1880                                              8
1890                                              9
1900                                             14
1910                                             14
1920                                             15
1930                                             18
1940                                             18
1950                                             22
1960                                             24
1970                                             25
1980                                             25
1990                                             25
2000                                             26
2010                                             27

In [9]:
file_name = "extinct_aus_mammals.csv"
path = "data"
exmam_df.to_csv(f"{path}/{file_name}")

In [10]:
exmam_file_df = pd.read_csv(f"{path}/{file_name}", index_col="Decade")
exmam_file_df

        Cumulative number of extinct mammal species
Decade
1790                                              0
1800                                              0
1810                                              0
1820                                              0
1830                                              0
1840                                              1
1850                                              3
1860                                              5
1870                                              7
1880                                              8
1890                                              9
1900                                             14
1910                                             14
1920                                             15
1930                                             18
1940                                             18
1950                                             22
1960                                             24
1970                                             25
1980                                             25
1990                                             25
2000                                             26
2010                                             27

In [11]:
excel_file = "extinct_aus_mammals.xlsx"
exmam_file_df.to_excel(f"{path}/{excel_file}")
exmam_file_df.to_excel(f"{path}/{excel_file}", index=False)

In [12]:
with open(f"{path}/{file_name}", "r") as fp:
    exmam_text = fp.read()

print(exmam_text)

Decade,Cumulative number of extinct mammal species
1790,0
1800,0
1810,0
1820,0
1830,0
1840,1
1850,3
1860,5
1870,7
1880,8
1890,9
1900,14
1910,14
1920,15
1930,18
1940,18
1950,22
1960,24
1970,25
1980,25
1990,25
2000,26
2010,27

In [13]:
exmam_text

'Decade,Cumulative number of extinct mammal species\n1790,0\n1800,0\n1810,0\n1820,0\n1830,0\n1840,1\n1850,3\n1860,5\n1870,7\n1880,8\n1890,9\n1900,14\n1910,14\n1920,15\n1930,18\n1940,18\n1950,22\n1960,24\n1970,25\n1980,25\n1990,25\n2000,26\n2010,27\n'

In [14]:
with open(f"{path}/{file_name}", "r") as fp:
    exmam_lines = fp.readlines()

print(exmam_lines)

['Decade,Cumulative number of extinct mammal species\n', '1790,0\n', '1800,0\n', '1810,0\n', '1820,0\n', '1830,0\n', '1840,1\n', '1850,3\n', '1860,5\n', '1870,7\n', '1880,8\n', '1890,9\n', '1900,14\n', '1910,14\n', '1920,15\n', '1930,18\n', '1940,18\n', '1950,22\n', '1960,24\n', '1970,25\n', '1980,25\n', '1990,25\n', '2000,26\n', '2010,27\n']

In [15]:
exmam_lines

['Decade,Cumulative number of extinct mammal species\n',
 '1790,0\n',
 '1800,0\n',
 '1810,0\n',
 '1820,0\n',
 '1830,0\n',
 '1840,1\n',
 '1850,3\n',
 '1860,5\n',
 '1870,7\n',
 '1880,8\n',
 '1890,9\n',
 '1900,14\n',
 '1910,14\n',
 '1920,15\n',
 '1930,18\n',
 '1940,18\n',
 '1950,22\n',
 '1960,24\n',
 '1970,25\n',
 '1980,25\n',
 '1990,25\n',
 '2000,26\n',
 '2010,27\n']

In [16]:
lines = exmam_text.split("\n")
lines

['Decade,Cumulative number of extinct mammal species',
 '1790,0',
 '1800,0',
 '1810,0',
 '1820,0',
 '1830,0',
 '1840,1',
 '1850,3',
 '1860,5',
 '1870,7',
 '1880,8',
 '1890,9',
 '1900,14',
 '1910,14',
 '1920,15',
 '1930,18',
 '1940,18',
 '1950,22',
 '1960,24',
 '1970,25',
 '1980,25',
 '1990,25',
 '2000,26',
 '2010,27',
 '']

In [17]:
lines = exmam_text.split("\n")

for line in lines:
    data_points = line.split(",")
    print(data_points)

['Decade', 'Cumulative number of extinct mammal species']
['1790', '0']
['1800', '0']
['1810', '0']
['1820', '0']
['1830', '0']
['1840', '1']
['1850', '3']
['1860', '5']
['1870', '7']
['1880', '8']
['1890', '9']
['1900', '14']
['1910', '14']
['1920', '15']
['1930', '18']
['1940', '18']
['1950', '22']
['1960', '24']
['1970', '25']
['1980', '25']
['1990', '25']
['2000', '26']
['2010', '27']
['']

In [18]:
import json

In [20]:
json_file_name = "simple_json_file.json"
path = "data"

with open(f"{path}/{json_file_name}", "r") as file:
    json_data = json.load(file)

print(json_data)

{'Key 1': 'The first value that goes with Key 1', 'Second key': 'Json data that goes with the second key', '3rd_key': ['This', 'is', 'a', 'json', 'list', 'and', 'value', 'for', '3rd key']}

In [23]:
json_data["Key 1"]

'The first value that goes with Key 1'

In [24]:
json_data.keys()

dict_keys(['Key 1', 'Second key', '3rd_key'])

In [25]:
for key in json_data.keys():
    print("key:", key)
    value = json_data[key]
    print("value:", value)
    print()

key: Key 1
value: The first value that goes with Key 1

key: Second key
value: Json data that goes with the second key

key: 3rd_key
value: ['This', 'is', 'a', 'json', 'list', 'and', 'value', 'for', '3rd key']

In [26]:
import requests

mammal_url = "https://data.gov.au/api/3/action/package_show?id=c02731e8-5327-4720-bbc7-1fe67350a569"

response = requests.get(mammal_url)
response.content

b'{"help": "https://data.gov.au/data/api/3/action/help_show?name=package_show", "success": true, "result": {"author": "CSIRO Publishing", "author_email": null, "contact_point": "soe@environment.gov.au", "creator_user_id": "dd537e79-7dfd-4a78-9110-8a42785bad1a", "duplicate_score": 1, "geospatial_topic": [], "id": "c02731e8-5327-4720-bbc7-1fe67350a569", "isopen": false, "language": "English", "license_id": "cc-by-4.0", "license_title": "Creative Commons Attribution 4.0 International", "license_url": "http://creativecommons.org/licenses/by/4.0", "maintainer": "soe", "maintainer_email": null, "metadata_created": "2016-10-13T05:31:05.905629", "metadata_modified": "2023-08-09T05:00:12.302898", "name": "2016-soe-biodiversity-cumulative-number-of-extinct-mammal-species", "notes": "Data on cumulative historical extinctions of Australian mammal species - according to the Action Plan for Australian Mammals (2014 edition) by John Woinarksi, Andrew Burbidge and Peter Harrison. CSIRO Publishing.\\r\\n\\r\\nThis data was used by the Department of Environment and Energy to produce Figure BIO19 in the Biodiversity theme of Australia State of the Environment 2016, available at \\r\\nhttps://soe.environment.gov.au/theme/biodiversity/topic/2016/terrestrial-plant-and-animal-species-mammals#biodiversity-figure-BIO19\\r\\n", "num_resources": 1, "num_tags": 10, "organization": {"id": "c416b1b6-1ea1-47c3-b44a-b4586bee6e58", "name": "state-of-the-environment", "title": "State of the Environment", "type": "organization", "description": "", "image_url": "2017-01-25-001455.510982SOE2016LogoColour.png", "created": "2016-01-21T17:05:45.618925", "is_organization": true, "approval_status": "approved", "state": "active"}, "original_harvest_source": {"site_url": "https://data.gov.au/data/dataset/", "href": "https://data.gov.au/data/dataset/2016-soe-biodiversity-cumulative-number-of-extinct-mammal-species", "title": "data.gov.au"}, "owner_org": "c416b1b6-1ea1-47c3-b44a-b4586bee6e58", "private": false, "spatial_coverage": "Australia", "state": "active", "temporal_coverage_from": "2016-10-13 05:31:05", "title": "2016 SoE Biodiversity Cumulative historical extinctions of Australian mammal species", "type": "dataset", "unpublished": false, "url": null, "version": null, "extras": [{"key": "contact_info", "value": "false"}, {"key": "data_state", "value": "active"}, {"key": "field_of_research", "value": "[]"}, {"key": "jurisdiction", "value": "Commonwealth of Australia"}, {"key": "update_freq", "value": "infrequently"}], "resources": [{"cache_last_updated": null, "cache_url": null, "ckan_url": "https://data.gov.au", "created": "2016-10-13T16:31:36.178357", "datastore_active": true, "datastore_contains_all_records_of_source_file": true, "description": "Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\\r\\n\\r\\nNote: The extinction of 3 species\\u2014Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus\\u2014cannot be readily and reliably dated, and these are not included in the data.", "format": "CSV", "hash": "d9d6c23d4b14989a714e437602634ba8", "id": "8339c2b4-c763-4c50-a647-63935537453c", "ignore_hash": false, "last_modified": "2016-10-13T00:00:00", "metadata_modified": "2023-08-09T05:00:12.311402", "mimetype": null, "mimetype_inner": null, "name": "BIO19 Cumulative historical extinctions of Australian mammal species", "original_url": "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv", "package_id": "c02731e8-5327-4720-bbc7-1fe67350a569", "position": 0, "resource_id": "8339c2b4-c763-4c50-a647-63935537453c", "resource_type": null, "set_url_type": false, "size": null, "state": "active", "task_created": "2023-08-09 04:59:07.755538", "url": "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv", "url_type": "upload", "wms_layer": "", "zip_extract": false}], "tags": [{"display_name": "2016", "id": "1cdd2af1-833e-411c-8003-485b677d2f4d", "name": "2016", "state": "active", "vocabulary_id": null}, {"display_name": "2016 SoE", "id": "662eb96b-dedd-482a-bbed-6fe51a4783cb", "name": "2016 SoE", "state": "active", "vocabulary_id": null}, {"display_name": "Action Plan for Australian mammals", "id": "ab2fae4a-f38a-46b9-bd3b-f62f2b21aea5", "name": "Action Plan for Australian mammals", "state": "active", "vocabulary_id": null}, {"display_name": "Biodiversity", "id": "655e233e-355c-4311-b3ac-a06db4a3c237", "name": "Biodiversity", "state": "active", "vocabulary_id": null}, {"display_name": "SoE", "id": "6752f3e8-9a7a-4ffe-b9e7-9fce46be330f", "name": "SoE", "state": "active", "vocabulary_id": null}, {"display_name": "SoE Graph", "id": "ff1d16f8-8dfa-4c65-8bfc-3c5d53e0c385", "name": "SoE Graph", "state": "active", "vocabulary_id": null}, {"display_name": "State of the Environment", "id": "bfdd0f69-272e-49a1-b3b9-cabb8f586348", "name": "State of the Environment", "state": "active", "vocabulary_id": null}, {"display_name": "extinct", "id": "eef7a30a-2cec-4932-baf4-6ccf8d981b4b", "name": "extinct", "state": "active", "vocabulary_id": null}, {"display_name": "mammals", "id": "74b1d415-25b1-49f2-9274-b9626838f1c4", "name": "mammals", "state": "active", "vocabulary_id": null}, {"display_name": "species", "id": "2634e534-e803-4ea8-934d-50f936cf9073", "name": "species", "state": "active", "vocabulary_id": null}], "groups": [], "relationships_as_subject": [], "relationships_as_object": []}}'

In [28]:
mammal_json = response.json()
mammal_json

{'help': 'https://data.gov.au/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'author': 'CSIRO Publishing',
  'author_email': None,
  'contact_point': 'soe@environment.gov.au',
  'creator_user_id': 'dd537e79-7dfd-4a78-9110-8a42785bad1a',
  'duplicate_score': 1,
  'geospatial_topic': [],
  'id': 'c02731e8-5327-4720-bbc7-1fe67350a569',
  'isopen': False,
  'language': 'English',
  'license_id': 'cc-by-4.0',
  'license_title': 'Creative Commons Attribution 4.0 International',
  'license_url': 'http://creativecommons.org/licenses/by/4.0',
  'maintainer': 'soe',
  'maintainer_email': None,
  'metadata_created': '2016-10-13T05:31:05.905629',
  'metadata_modified': '2023-08-09T05:00:12.302898',
  'name': '2016-soe-biodiversity-cumulative-number-of-extinct-mammal-species',
  'notes': 'Data on cumulative historical extinctions of Australian mammal species - according to the Action Plan for Australian Mammals (2014 edition) by John Woinarksi, Andrew Burbidge and Peter Harrison. CSIRO Publishing.\r\n\r\nThis data was used by the Department of Environment and Energy to produce Figure BIO19 in the Biodiversity theme of Australia State of the Environment 2016, available at \r\nhttps://soe.environment.gov.au/theme/biodiversity/topic/2016/terrestrial-plant-and-animal-species-mammals#biodiversity-figure-BIO19\r\n',
  'num_resources': 1,
  'num_tags': 10,
  'organization': {'id': 'c416b1b6-1ea1-47c3-b44a-b4586bee6e58',
   'name': 'state-of-the-environment',
   'title': 'State of the Environment',
   'type': 'organization',
   'description': '',
   'image_url': '2017-01-25-001455.510982SOE2016LogoColour.png',
   'created': '2016-01-21T17:05:45.618925',
   'is_organization': True,
   'approval_status': 'approved',
   'state': 'active'},
  'original_harvest_source': {'site_url': 'https://data.gov.au/data/dataset/',
   'href': 'https://data.gov.au/data/dataset/2016-soe-biodiversity-cumulative-number-of-extinct-mammal-species',
   'title': 'data.gov.au'},
  'owner_org': 'c416b1b6-1ea1-47c3-b44a-b4586bee6e58',
  'private': False,
  'spatial_coverage': 'Australia',
  'state': 'active',
  'temporal_coverage_from': '2016-10-13 05:31:05',
  'title': '2016 SoE Biodiversity Cumulative historical extinctions of Australian mammal species',
  'type': 'dataset',
  'unpublished': False,
  'url': None,
  'version': None,
  'extras': [{'key': 'contact_info', 'value': 'false'},
   {'key': 'data_state', 'value': 'active'},
   {'key': 'field_of_research', 'value': '[]'},
   {'key': 'jurisdiction', 'value': 'Commonwealth of Australia'},
   {'key': 'update_freq', 'value': 'infrequently'}],
  'resources': [{'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.gov.au',
    'created': '2016-10-13T16:31:36.178357',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\r\n\r\nNote: The extinction of 3 species—Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus—cannot be readily and reliably dated, and these are not included in the data.',
    'format': 'CSV',
    'hash': 'd9d6c23d4b14989a714e437602634ba8',
    'id': '8339c2b4-c763-4c50-a647-63935537453c',
    'ignore_hash': False,
    'last_modified': '2016-10-13T00:00:00',
    'metadata_modified': '2023-08-09T05:00:12.311402',
    'mimetype': None,
    'mimetype_inner': None,
    'name': 'BIO19 Cumulative historical extinctions of Australian mammal species',
    'original_url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
    'package_id': 'c02731e8-5327-4720-bbc7-1fe67350a569',
    'position': 0,
    'resource_id': '8339c2b4-c763-4c50-a647-63935537453c',
    'resource_type': None,
    'set_url_type': False,
    'size': None,
    'state': 'active',
    'task_created': '2023-08-09 04:59:07.755538',
    'url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
    'url_type': 'upload',
    'wms_layer': '',
    'zip_extract': False}],
  'tags': [{'display_name': '2016',
    'id': '1cdd2af1-833e-411c-8003-485b677d2f4d',
    'name': '2016',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': '2016 SoE',
    'id': '662eb96b-dedd-482a-bbed-6fe51a4783cb',
    'name': '2016 SoE',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'Action Plan for Australian mammals',
    'id': 'ab2fae4a-f38a-46b9-bd3b-f62f2b21aea5',
    'name': 'Action Plan for Australian mammals',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'Biodiversity',
    'id': '655e233e-355c-4311-b3ac-a06db4a3c237',
    'name': 'Biodiversity',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'SoE',
    'id': '6752f3e8-9a7a-4ffe-b9e7-9fce46be330f',
    'name': 'SoE',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'SoE Graph',
    'id': 'ff1d16f8-8dfa-4c65-8bfc-3c5d53e0c385',
    'name': 'SoE Graph',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'State of the Environment',
    'id': 'bfdd0f69-272e-49a1-b3b9-cabb8f586348',
    'name': 'State of the Environment',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'extinct',
    'id': 'eef7a30a-2cec-4932-baf4-6ccf8d981b4b',
    'name': 'extinct',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'mammals',
    'id': '74b1d415-25b1-49f2-9274-b9626838f1c4',
    'name': 'mammals',
    'state': 'active',
    'vocabulary_id': None},
   {'display_name': 'species',
    'id': '2634e534-e803-4ea8-934d-50f936cf9073',
    'name': 'species',
    'state': 'active',
    'vocabulary_id': None}],
  'groups': [],
  'relationships_as_subject': [],
  'relationships_as_object': []}}

In [29]:
mammal_json.keys()

dict_keys(['help', 'success', 'result'])

In [30]:
mammal_json["result"].keys()

dict_keys(['author', 'author_email', 'contact_point', 'creator_user_id', 'duplicate_score', 'geospatial_topic', 'id', 'isopen', 'language', 'license_id', 'license_title', 'license_url', 'maintainer', 'maintainer_email', 'metadata_created', 'metadata_modified', 'name', 'notes', 'num_resources', 'num_tags', 'organization', 'original_harvest_source', 'owner_org', 'private', 'spatial_coverage', 'state', 'temporal_coverage_from', 'title', 'type', 'unpublished', 'url', 'version', 'extras', 'resources', 'tags', 'groups', 'relationships_as_subject', 'relationships_as_object'])

In [32]:
mammal_json["result"]["resources"][0]

{'cache_last_updated': None,
 'cache_url': None,
 'ckan_url': 'https://data.gov.au',
 'created': '2016-10-13T16:31:36.178357',
 'datastore_active': True,
 'datastore_contains_all_records_of_source_file': True,
 'description': 'Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\r\n\r\nNote: The extinction of 3 species—Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus—cannot be readily and reliably dated, and these are not included in the data.',
 'format': 'CSV',
 'hash': 'd9d6c23d4b14989a714e437602634ba8',
 'id': '8339c2b4-c763-4c50-a647-63935537453c',
 'ignore_hash': False,
 'last_modified': '2016-10-13T00:00:00',
 'metadata_modified': '2023-08-09T05:00:12.311402',
 'mimetype': None,
 'mimetype_inner': None,
 'name': 'BIO19 Cumulative historical extinctions of Australian mammal species',
 'original_url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
 'package_id': 'c02731e8-5327-4720-bbc7-1fe67350a569',
 'position': 0,
 'resource_id': '8339c2b4-c763-4c50-a647-63935537453c',
 'resource_type': None,
 'set_url_type': False,
 'size': None,
 'state': 'active',
 'task_created': '2023-08-09 04:59:07.755538',
 'url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
 'url_type': 'upload',
 'wms_layer': '',
 'zip_extract': False}

In [33]:
metadata = json.dumps(mammal_json["result"]["resources"][0])
metadata

'{"cache_last_updated": null, "cache_url": null, "ckan_url": "https://data.gov.au", "created": "2016-10-13T16:31:36.178357", "datastore_active": true, "datastore_contains_all_records_of_source_file": true, "description": "Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\\r\\n\\r\\nNote: The extinction of 3 species\\u2014Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus\\u2014cannot be readily and reliably dated, and these are not included in the data.", "format": "CSV", "hash": "d9d6c23d4b14989a714e437602634ba8", "id": "8339c2b4-c763-4c50-a647-63935537453c", "ignore_hash": false, "last_modified": "2016-10-13T00:00:00", "metadata_modified": "2023-08-09T05:00:12.311402", "mimetype": null, "mimetype_inner": null, "name": "BIO19 Cumulative historical extinctions of Australian mammal species", "original_url": "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv", "package_id": "c02731e8-5327-4720-bbc7-1fe67350a569", "position": 0, "resource_id": "8339c2b4-c763-4c50-a647-63935537453c", "resource_type": null, "set_url_type": false, "size": null, "state": "active", "task_created": "2023-08-09 04:59:07.755538", "url": "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv", "url_type": "upload", "wms_layer": "", "zip_extract": false}'

In [35]:
file_name = "extinct_mammals_metadata.json"

with open(f"{path}/{file_name}", "w") as fp:
    fp.write(metadata)

with open(f"{path}/{file_name}", "r") as fp:
    text = fp.read()
    file_json = json.loads(text)

file_json

{'cache_last_updated': None,
 'cache_url': None,
 'ckan_url': 'https://data.gov.au',
 'created': '2016-10-13T16:31:36.178357',
 'datastore_active': True,
 'datastore_contains_all_records_of_source_file': True,
 'description': 'Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\r\n\r\nNote: The extinction of 3 species—Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus—cannot be readily and reliably dated, and these are not included in the data.',
 'format': 'CSV',
 'hash': 'd9d6c23d4b14989a714e437602634ba8',
 'id': '8339c2b4-c763-4c50-a647-63935537453c',
 'ignore_hash': False,
 'last_modified': '2016-10-13T00:00:00',
 'metadata_modified': '2023-08-09T05:00:12.311402',
 'mimetype': None,
 'mimetype_inner': None,
 'name': 'BIO19 Cumulative historical extinctions of Australian mammal species',
 'original_url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
 'package_id': 'c02731e8-5327-4720-bbc7-1fe67350a569',
 'position': 0,
 'resource_id': '8339c2b4-c763-4c50-a647-63935537453c',
 'resource_type': None,
 'set_url_type': False,
 'size': None,
 'state': 'active',
 'task_created': '2023-08-09 04:59:07.755538',
 'url': 'https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv',
 'url_type': 'upload',
 'wms_layer': '',
 'zip_extract': False}

In [37]:
mammal_json["result"]["resources"][0].keys()

dict_keys(['cache_last_updated', 'cache_url', 'ckan_url', 'created', 'datastore_active', 'datastore_contains_all_records_of_source_file', 'description', 'format', 'hash', 'id', 'ignore_hash', 'last_modified', 'metadata_modified', 'mimetype', 'mimetype_inner', 'name', 'original_url', 'package_id', 'position', 'resource_id', 'resource_type', 'set_url_type', 'size', 'state', 'task_created', 'url', 'url_type', 'wms_layer', 'zip_extract'])

In [38]:
mammal_json["result"]["resources"][0]["description"]

'Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.\r\n\r\nNote: The extinction of 3 species—Bettongia pusilla, Conilurus capricornensis and Pseudomys glaucus—cannot be readily and reliably dated, and these are not included in the data.'

In [39]:
mammal_json["result"]["resources"][0]["description"].split("\r\n")[0]

'Source: Woinarski, JCZ, Burbidge, AA & Harrison PL (2014 edition). The action plan for Australian mammals 2012, CSIRO Publishing, Melbourne.'

In [41]:
mammal_json["result"]["notes"]

'Data on cumulative historical extinctions of Australian mammal species - according to the Action Plan for Australian Mammals (2014 edition) by John Woinarksi, Andrew Burbidge and Peter Harrison. CSIRO Publishing.\r\n\r\nThis data was used by the Department of Environment and Energy to produce Figure BIO19 in the Biodiversity theme of Australia State of the Environment 2016, available at \r\nhttps://soe.environment.gov.au/theme/biodiversity/topic/2016/terrestrial-plant-and-animal-species-mammals#biodiversity-figure-BIO19\r\n'

In [43]:
notes = mammal_json["result"]["notes"]
struct_notes = notes.split("\r\n")

for note in struct_notes:
    print(note)

Data on cumulative historical extinctions of Australian mammal species - according to the Action Plan for Australian Mammals (2014 edition) by John Woinarksi, Andrew Burbidge and Peter Harrison. CSIRO Publishing.

This data was used by the Department of Environment and Energy to produce Figure BIO19 in the Biodiversity theme of Australia State of the Environment 2016, available at
https://soe.environment.gov.au/theme/biodiversity/topic/2016/terrestrial-plant-and-animal-species-mammals#biodiversity-figure-BIO19