In [2]:
import pandas as pd

extinct_mammals_url = "https://data.gov.au/data/dataset/c02731e8-5327-4720-bbc7-1fe67350a569/resource/8339c2b4-c763-4c50-a647-63935537453c/download/cumulative-number-of-extinct-mammal-species.csv"
exmam_df = pd.read_csv(extinct_mammals_url, index_col="Decade")
exmam_df

        Cumulative number of extinct mammal species
Decade
1790                                              0
1800                                              0
1810                                              0
1820                                              0
1830                                              0
1840                                              1
1850                                              3
1860                                              5
1870                                              7
1880                                              8
1890                                              9
1900                                             14
1910                                             14
1920                                             15
1930                                             18
1940                                             18
1950                                             22
1960                                             24
1970                                             25
1980                                             25
1990                                             25
2000                                             26
2010                                             27

In [3]:
file_name = "extinct_aus_mammals.csv"
path = "data"
exmam_df.to_csv(f"{path}/{file_name}")

In [6]:
exmam_file_df = pd.read_csv(f"{path}/{file_name}", index_col="Decade")
exmam_file_df

        Cumulative number of extinct mammal species
Decade
1790                                              0
1800                                              0
1810                                              0
1820                                              0
1830                                              0
1840                                              1
1850                                              3
1860                                              5
1870                                              7
1880                                              8
1890                                              9
1900                                             14
1910                                             14
1920                                             15
1930                                             18
1940                                             18
1950                                             22
1960                                             24
1970                                             25
1980                                             25
1990                                             25
2000                                             26
2010                                             27

In [8]:
excel_file = "extinct_aus_mammals.xlsx"
exmam_file_df.to_excel(f"{path}/{excel_file}")
exmam_file_df.to_excel(f"{path}/{excel_file}", index=False)

In [9]:
with open(f"{path}/{file_name}", "r") as fp:
    exmam_text = fp.read()

print(exmam_text)

Decade,Cumulative number of extinct mammal species
1790,0
1800,0
1810,0
1820,0
1830,0
1840,1
1850,3
1860,5
1870,7
1880,8
1890,9
1900,14
1910,14
1920,15
1930,18
1940,18
1950,22
1960,24
1970,25
1980,25
1990,25
2000,26
2010,27

In [11]:
exmam_text

'Decade,Cumulative number of extinct mammal species\n1790,0\n1800,0\n1810,0\n1820,0\n1830,0\n1840,1\n1850,3\n1860,5\n1870,7\n1880,8\n1890,9\n1900,14\n1910,14\n1920,15\n1930,18\n1940,18\n1950,22\n1960,24\n1970,25\n1980,25\n1990,25\n2000,26\n2010,27\n'

In [12]:
with open(f"{path}/{file_name}", "r") as fp:
    exmam_lines = fp.readlines()

print(exmam_lines)

['Decade,Cumulative number of extinct mammal species\n', '1790,0\n', '1800,0\n', '1810,0\n', '1820,0\n', '1830,0\n', '1840,1\n', '1850,3\n', '1860,5\n', '1870,7\n', '1880,8\n', '1890,9\n', '1900,14\n', '1910,14\n', '1920,15\n', '1930,18\n', '1940,18\n', '1950,22\n', '1960,24\n', '1970,25\n', '1980,25\n', '1990,25\n', '2000,26\n', '2010,27\n']

In [13]:
exmam_lines

['Decade,Cumulative number of extinct mammal species\n',
 '1790,0\n',
 '1800,0\n',
 '1810,0\n',
 '1820,0\n',
 '1830,0\n',
 '1840,1\n',
 '1850,3\n',
 '1860,5\n',
 '1870,7\n',
 '1880,8\n',
 '1890,9\n',
 '1900,14\n',
 '1910,14\n',
 '1920,15\n',
 '1930,18\n',
 '1940,18\n',
 '1950,22\n',
 '1960,24\n',
 '1970,25\n',
 '1980,25\n',
 '1990,25\n',
 '2000,26\n',
 '2010,27\n']

In [15]:
lines = exmam_text.split("\n")
lines

['Decade,Cumulative number of extinct mammal species',
 '1790,0',
 '1800,0',
 '1810,0',
 '1820,0',
 '1830,0',
 '1840,1',
 '1850,3',
 '1860,5',
 '1870,7',
 '1880,8',
 '1890,9',
 '1900,14',
 '1910,14',
 '1920,15',
 '1930,18',
 '1940,18',
 '1950,22',
 '1960,24',
 '1970,25',
 '1980,25',
 '1990,25',
 '2000,26',
 '2010,27',
 '']

In [16]:
lines = exmam_text.split("\n")

for line in lines:
    data_points = line.split(",")
    print(data_points)

['Decade', 'Cumulative number of extinct mammal species']
['1790', '0']
['1800', '0']
['1810', '0']
['1820', '0']
['1830', '0']
['1840', '1']
['1850', '3']
['1860', '5']
['1870', '7']
['1880', '8']
['1890', '9']
['1900', '14']
['1910', '14']
['1920', '15']
['1930', '18']
['1940', '18']
['1950', '22']
['1960', '24']
['1970', '25']
['1980', '25']
['1990', '25']
['2000', '26']
['2010', '27']
['']

In [17]:
import json

In [ ]:
json_file_name = "simple_jason_file.json"
path = "data"

with open(f"{path}/{json_file_name}", "r") as file:
    json_data = json.load(file)

print)