In [9]:
import pandas as pd
import plotly.express as px

file_path = "data/"
file_name = "indicator-4-2-0-4.csv"
df = pd.read_csv(f"{file_path}{file_name}")
df

     Year  Month  Cape Ferguson  Rosslyn Bay  Global
0    1996      1           60.0           73     0.0
1    1996      2          115.0          145    -0.3
2    1996      3          132.0           89     3.7
3    1996      4            2.0           40     2.9
4    1996      5           26.0           56     4.8
..    ...    ...            ...          ...     ...
285  2019     10           19.0           44    90.7
286  2019     11           13.0           18    90.8
287  2019     12           90.0          111     NaN
288  2020      1          127.0          125     NaN
289  2020      2          162.0          166     NaN

[290 rows x 5 columns]

In [10]:
df.groupby("Year").size()

Year
1996    12
1997    12
1998    12
1999    12
2000    12
2001    12
2002    12
2003    12
2004    12
2005    12
2006    12
2007    12
2008    12
2009    12
2010    12
2011    12
2012    12
2013    12
2014    12
2015    12
2016    12
2017    12
2018    12
2019    12
2020     2
dtype: int64

In [11]:
clean_df = df[df["Year"] < 2020]
clean_df

     Year  Month  Cape Ferguson  Rosslyn Bay  Global
0    1996      1           60.0           73     0.0
1    1996      2          115.0          145    -0.3
2    1996      3          132.0           89     3.7
3    1996      4            2.0           40     2.9
4    1996      5           26.0           56     4.8
..    ...    ...            ...          ...     ...
283  2019      8           35.0           49    92.2
284  2019      9           10.0           25    91.6
285  2019     10           19.0           44    90.7
286  2019     11           13.0           18    90.8
287  2019     12           90.0          111     NaN

[288 rows x 5 columns]

In [13]:
mean_cols = ["Cape Ferguson", "Rosslyn Bay", "Global"]
mean_df = clean_df.groupby("Year")[mean_cols].mean()
mean_df

      Cape Ferguson  Rosslyn Bay     Global
Year
1996     -11.083333     7.833333   4.400000
1997     -21.666667    -7.750000   8.950000
1998      52.250000    43.250000  14.466667
1999      53.166667    61.416667  14.583333
2000      51.916667    40.166667  17.908333
2001      26.500000    36.250000  22.491667
2002       4.416667    15.916667  25.975000
2003      17.958333    34.750000  28.158333
2004      -8.833333     3.000000  30.216667
2005      -0.250000    32.500000  34.025000
2006      16.833333    11.166667  35.725000
2007      40.000000    20.500000  36.141667
2008      19.083333    36.666667  41.341667
2009      59.416667    47.500000  45.725000
2010     119.000000   111.416667  47.808333
2011      99.083333   100.583333  46.891667
2012      66.416667    76.166667  57.250000
2013      82.250000   119.333333  60.691667
2014      76.833333   101.000000  63.516667
2015      59.750000    87.750000  73.183333
2016      84.333333   103.500000  78.050000
2017      96.000000   123.416667  79.525000
2018      94.916667   121.250000  83.366667
2019     112.083333   115.833333  90.354545

In [15]:
fig = px.line(mean_df, width=800, height=400)
fig.show()